joystick:
  ros__parameters:
    #use_sim_time: true    # zakomentowane ze wzglÄ™du na nagrywanie cmd_vel poprzez ros2 bag
    device_id: 0
    device_name: ""
    deadzon: 0.5
    autorepeat_rate: 20.0
    sticky_buttons: false
    coalesce_interval_ms: 1