slam_toolbox:
  ros__parameters:
    use_sim_time: true

    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link"

    scan_topic: "/scan"
    odom_topic: "slambot_controller/odom"

    mode: "mapping"

    map_update_interval: 1.0  
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.0

    scan_buffer_size: 5       # dla prawdziwie synchronicznego - bardzo du≈ºa liczba
    tf_buffer_duration: 10.

    resolution: 0.05               
    max_laser_range: 12.0          